Merge pull request #4836 from overleaf/jk-fetch-json-error-message
FetchError: set error message when statusText it missing
GitOrigin-RevId: 05461a6918af3ee339e66df2abc48635a082f6b7